pipeline {
    agent any

    parameters {
        choice(choices: ['option', 'kubectl apply', 'kubectl delete'], name: 'DEPLOY_COMMAND', description: '배포 타입 선택')
    }

    environment {
        INSTALL_PATH = 'calico'
    }

    stages {
        stage('deploy calico') {
            steps {
                script{
                    sh "${params.DEPLOY_COMMAND} -f ${INSTALL_PATH}/calico.yaml"
                    sh "${params.DEPLOY_COMMAND} -f ${INSTALL_PATH}/calico-custom.yaml"
                }
            }
        }
    }
}