apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
spec:
  storageClassName: "vault-storage"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: vault-pv

