pipeline {
    agent any

    parameters {
        choice(choices: ['option', 'kubectl apply', 'kubectl delete'], name: 'DEPLOY_COMMAND', description: '배포 타입 선택')
    }

    environment {
        INSTALL_PATH = 'metric-server'
    }

    stages {
        stage('deploy k8s metric-server') {
            steps {
                script{
                    sh "${params.DEPLOY_COMMAND} -f ${INSTALL_PATH}/metric-server.yaml"
                }
            }
        }
    }
}